/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:46a236bc-a54a-4384-a150-b93d8786cd4f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_tHgAsDpfM",
    "aws_user_pools_web_client_id": "19gtcgicvtrfv54bj7gan9rocg",
    "oauth": {}
};


export default awsmobile;
